-- ============================================================
-- Migration 002: Calendar & Booking tables
-- GreenPlus Ai — PRD Section 18
-- ============================================================

-- Shop's weekly regular schedule
CREATE TABLE shop_hours (
  id          uuid     PRIMARY KEY DEFAULT gen_random_uuid(),
  shop_id     uuid     NOT NULL REFERENCES shops(id) ON DELETE CASCADE,
  day_of_week smallint NOT NULL CHECK (day_of_week BETWEEN 0 AND 6),
  open_time   time     NOT NULL,
  close_time  time     NOT NULL,
  is_open     boolean  NOT NULL DEFAULT true,
  UNIQUE (shop_id, day_of_week)
);

-- Shop closures: one-time, multi-day, or recurring
CREATE TABLE shop_closures (
  id               uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  shop_id          uuid        NOT NULL REFERENCES shops(id) ON DELETE CASCADE,
  start_date       date        NOT NULL,
  end_date         date        NOT NULL,
  recurrence_type  text        NOT NULL DEFAULT 'none'
                   CHECK (recurrence_type IN ('none', 'weekly', 'monthly_date', 'annual')),
  recurrence_end   date,
  reason           text,
  created_at       timestamptz DEFAULT now(),
  CONSTRAINT end_after_start CHECK (end_date >= start_date)
);

-- Pre-generated bookable time slots (generated by Edge Function nightly)
CREATE TABLE time_slots (
  id           uuid     PRIMARY KEY DEFAULT gen_random_uuid(),
  shop_id      uuid     NOT NULL REFERENCES shops(id) ON DELETE CASCADE,
  date         date     NOT NULL,
  start_time   time     NOT NULL,
  end_time     time     NOT NULL,
  capacity     smallint NOT NULL DEFAULT 3,
  booked_count smallint NOT NULL DEFAULT 0,
  UNIQUE (shop_id, date, start_time),
  CONSTRAINT capacity_positive CHECK (capacity > 0),
  CONSTRAINT count_not_negative CHECK (booked_count >= 0)
);

-- Bookings
CREATE TABLE bookings (
  id             uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id        uuid        NOT NULL REFERENCES user_profiles(id) ON DELETE CASCADE,
  shop_id        uuid        NOT NULL REFERENCES shops(id),
  slot_id        uuid        NOT NULL REFERENCES time_slots(id),
  materials      jsonb       NOT NULL,  -- [{ materialType, grade, weight_kg }]
  total_estimate numeric(10,2),
  status         text        NOT NULL DEFAULT 'pending'
                 CHECK (status IN ('pending', 'confirmed', 'rejected', 'cancelled', 'completed')),
  note           text,
  created_at     timestamptz DEFAULT now(),
  updated_at     timestamptz DEFAULT now()
);
